### ISSUE TITLE
CFP from Yaroslav Tkachenko:Building Stateful Microservices With Akka

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#108]
---

name: Yaroslav Tkachenko
title: Building Stateful Microservices With Akka
length: 40 minutes
audience: Advanced: Well acquainted with the domain, little introductory material included in the talk
language: English
twitter: sap1ens
github: sap1ens
icon: 
organization: Bench Accounting
tags:
##   - Software Design and Architecture, Microservices

It seems like all the dust about microservices has finally settled. We know how to design, develop and operate them. Although most of the microservices are stateless - they delegate things like persistence and consistency to a database. But sometimes you benefit when you keep the state inside the application.

In this presentation I’m going to talk about why you want to build stateful microservices and design choices you make. I’ll explain tools like Akka Clustering and Akka Persistence in depth and show a few practical examples.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
