### ISSUE TITLE
CFP from Denys Shabalin:Coding up your first game in Scala Native

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#113]
---

name: Denys Shabalin
title: Coding up your first game in Scala Native
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: https://twitter.com/den_sh
github: http://github.com/densh
icon: 
organization: EPFL
tags:
##   - Others

This talk is going to walk you through the development of a simple game using Scala Native from the bare basics. It will cover a number of topics, starting from the initial project setup, explain how to interoperate with native code and ultimately get your game running.

No prior knowledge of Scala Native is required. Beginner-level familiarity with C is recommended.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
