### ISSUE TITLE
CFP from 岡田遥来 : ScalikeJDBC入門

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#125]
---

name: 岡田遥来
title: ScalikeJDBC入門
length: 40 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: ocadaruma
github: ocadaruma
icon: 
organization: 株式会社オプト
tags:
##   - Tools

ScalaのDBライブラリは色々ありますが、その中でも、発行されるSQLの分かりやすさや複雑なSQLにも対応可能な柔軟性から、ScalikeJDBCは有力な選択肢です。

このセッションでは、ScalikeJDBCの基本要素から始めて、サブクエリを含んだ複雑なクエリの組み立て方、および実際に導入する上でのTIPSなどをご紹介します。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
