### ISSUE TITLE
CFP from Felix Mulder:Dotty and the new Scala Developer Experience

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#132]
---
name: Felix Mulder
title: Dotty and the new Scala Developer Experience
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: felixmulder
github: felixmulder
icon: 
organization: EPFL
tags:
  - Others

---
The new Scala compiler is nearing beta readiness. A lot of thought has gone into designing Dotty to be as fast and structurally sound as possible. Now comes the next step - adding a new level of usability to the compiler and the surrounding tools.

In this talk I want to show what Dotty can offer you as a developer in terms of improved experience - whether it is awesome error messages, rewrite rules or optimizations.

I will also talk about how we are optimizing the project for outside contributors, and what you can do to get involved today!

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
