### ISSUE TITLE
CFP from Tomer Gabel :Java 8 and Beyond, a Scala Story

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#134]
---
name: Tomer Gabel 
title: Java 8 and Beyond, a Scala Story
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: tomerg
github: holograph
icon: 
organization: Wix
tags:
  - Intro to Scala

---
With Java 8 adoption skyrocketing, is Scala still relevant? In our opinion, the answer is an unequivocal yes. To make our point, Tomer Gabel (system architect at Wix) will showcase practical examples where Scala's features provide a definitive advantage over Java 8. We'll cover:

* Effective logging with traits and by-name parameters;
* Pattern matching for fun and profit;
* Type-safe, efficient serialization with type classes.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
