### ISSUE TITLE
CFP from Tomer Gabel:Functional Leap of Faith

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#135]
---
name: Tomer Gabel
title: Functional Leap of Faith
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: tomerg
github: holograph
icon: 
organization: Wix
tags:
  - Functional Programming, Software Design and Architecture

---
Some say there's nothing new under the sun, but looking back on six decades of computing, it's easy to see that is not the case. Structured programming, originating in the '60s, did not gain mainstream adoption until the '80s; object-oriented programming was hotly debated in the '70s but only became widespread in the '90s. Every couple of decades sees an engineering leap that radically improves the software engineering discipline.

I believe we are now at such an inflection point, with functional programming concepts slowly sifting into the mainstream. After this talk, I hope you will too.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
