### ISSUE TITLE
CFP from Tomer Gabel:Scala Back to Basics: Type Classes

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#136]
---
name: Tomer Gabel
title: Scala Back to Basics: Type Classes
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: tomerg
github: holograph
icon: 
organization: Wix
tags:
  - Intro to Scala

---
Type classes are a fundamental feature of Scala, which allows you to layer new functionality on top of existing types externally, i.e. without modifying or recompiling existing code. When combined with implicits, this is a truly remarkable tool that enables many of the advanced features offered by the Scala library ecosystem. In this talk we'll go back to basics: how type classes are defined and encoded, and cover several prominent use cases. While geared towards beginners, a revisit of this topic may prove useful to veteran Scala developers as well.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
