### ISSUE TITLE
CFP from Jon Pretty:Interpolating Strings Like A Boss

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#141]
---
name: Jon Pretty
title: Interpolating Strings Like A Boss
length: 40 minutes
audience: Advanced: Well acquainted with the domain, little introductory material included in the talk
language: English
twitter: propensive
github: propensive
icon: 
organization: Propensive Ltd
tags:
  - Intro to Scala, Software Design and Architecture, Others

---
Most people are familiar with the `s"Hello, $name"` syntax for composing strings, but that only touches the surface of what is possible in Scala. By combining it with other Scala features like advanced types, implicits and macros, we introduce many interesting opportunities for powerful and typesafe embedded DSLs, both large and small.

The talk will be presented in four levels of increasing difficulty—value level, type level, macro level, and "boss level"—so beginners and advanced users should all learn something new!

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
