### ISSUE TITLE
CFP from Choucri FAHED:Play with Elm!

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#145]
---
name: Choucri FAHED
title: Play with Elm!
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: @choucrifahed
github: https://github.com/choucrifahed
icon: 
organization: 
tags:
  - Functional Programming

---
Elm is a simple and fun language for writing rich and robust web applications. Elm generates performant JavaScript, with the promise of no runtime errors. In this presentation, I will briefly introduce the language, it's architecture, then show why it makes sense to use it with Scala. Thus oppose it to Scala.js, and demo a Play web application through the sbt-elm plugin.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
