### ISSUE TITLE
CFP from Michael Cohen:The Art of Functional Programming

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#146]
---
name: Michael Cohen
title: The Art of Functional Programming
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: @gothamtechtalk
github: 
icon: 
organization: CPI
tags:
  - Best Practices, Software Design and Architecture, Others

---
Software Engineering is like Art (music / visual arts) in that they are the only two areas of human study that do not have a "correct way" of doing things, but in fact, do have "wrong ways" of doing things.  

There are many different roles within art as there are within software engineering - see the parallels between the two and understand where/how you fit in.

There is beauty in art, as there is beauty in software engineering - this talk delves into what makes art beautiful, and how software engineers can employ the same tactics to make their code beautiful.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
