### ISSUE TITLE
CFP from うらがみ : Javaプログラマが型クラスに入門した話

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#147]
---
name: うらがみ
title: Javaプログラマが型クラスに入門した話
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: backpaper0
github: backpaper0
icon: 
organization: 
tags:
  - Intro to Scala

---
Javaプログラマである私がHaskellの型クラスと、それに相当するScalaのimplicit parameterの使い方を理解できた気がするので、型クラスとはどんなものなのか？という事を私なりに解説したいと思います。
JavaやScalaのclassとの違いが分からない！とか、implicit parameterこわい！といった方にも一緒に入門して貰えるような話にするつもりです。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
