### ISSUE TITLE
CFP from やんく : KotlinからはじめるScala

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#151]
---
name: やんく
title: KotlinからはじめるScala
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: yy_yank
github: yyYank
icon: 
organization: Japan Java User Group, Japan Kotlin User Group
tags:
  - Intro to Scala

---

私はScalaという言語に難しい"印象"を持っており独習出来ていませんでした。

そんな中、Kotlinという言語を学ぶきっかけがあり、何日か費やして基本文法を学び関連イベントで発表したり情報発信するようになりました。

その後、Scalaのコードを見た時、Scalaとの距離がぐっと縮まったように感じ以前よりスムーズに基本文法を抑える事ができました。まだまだ未熟ですがScalaで趣味アプリケーションを作るぐらいは出来る程度になりました。

本トークではKotlinを学んでからScalaを学ぶという学習ルートの可能性についてと、注意すべき点を話したいと思います。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
