### ISSUE TITLE
CFP from 中山裕貴 : Free, Free Applicativeを用いたユニットテスティングフレームワークの実装

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#154]
---
name: 中山裕貴
title: Free, Free Applicativeを用いたユニットテスティングフレームワークの実装
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: pocketberserker
github: pocketberserker
icon: 
organization: 
tags:
  - Functional Programming

---
FreeやFree Applicativeは様々な場面で利用されています。ユニットテスティングフレームワークも適用範囲の一つだと考えています。本発表では、FreeやFree Applicativeを用いたテストDSLの設計、実装について解説します。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
