### ISSUE TITLE
CFP from 中山裕貴 : ”私、ScalaMatsuriで転職しました”を振り返る

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#155]
---
name: 中山裕貴
title: ”私、ScalaMatsuriで転職しました”を振り返る
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: pocketberserker
github: pocketberserker
icon: 
organization: 
tags:
  - Others

---
”私、ScalaMatsuriで転職しました”というインタビュー記事が掲載されてから1年以上が経過しました。
あのインタビューで語られたことは今でも通用するのでしょうか？
インタビュイーはあの記事を見直して何を思うのでしょう？
本トークでは当時を振り返りながら、現在のScala界隈の情勢について考察します。

※ 発表者はScalaMatsuriスタッフではありません

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
