### ISSUE TITLE
CFP from Jacek Kunicki:A Practical Introduction to Akka Streams

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#168]
---
name: Jacek Kunicki
title: A Practical Introduction to Akka Streams
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: rucek
github: rucek
icon: 
organization: SoftwareMill
tags:
  - Big Data / Fast Data, Tools

---
Stream processing is a hot topic today and it’s easy to get lost among all the possibilities. In this live coding session we will explore the Reactive Streams approach used by the Akka Streams project. On an almost real-life example we’re going to walk through both the basics and some more advanced usages of the library.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
