### ISSUE TITLE
スポンサーロゴのプレースホルダがスポンサー様ロゴと合わせて並び替えられる

### ISSUE THREAD

**Issue by tkawachi** [scalajp/2017.scalamatsuri.org#17]
スポンサー様は左上から詰めて表示したほうが良いように思いますがどうでしょうか。

![screen shot 2016-10-06 at 22 09 41](https://cloud.githubusercontent.com/assets/22657/19153465/a8481fba-8c11-11e6-8198-b4aa76b819c4.png)

**Comment by taisukeoe** [comment]
というか１件以上申し込みがあったプランについては、place holder削除していい気がします

**Comment by tkawachi** [comment]
> というか１件以上申し込みがあったプランについては、place holder削除

という方針で進んでいるので閉じます。
