### ISSUE TITLE
CFP from 竹添 直樹 : Scala WarriorにおけるScala.jsとタイプセーフなWeb開発

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#171]
---
name: 竹添 直樹
title: Scala WarriorにおけるScala.jsとタイプセーフなWeb開発
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: takezoen
github: takezoe
icon: 
organization: 株式会社ビズリーチ
tags:
  - Others

---
Scala Warriorはユーザが入力したScalaコードで侍を動かして戦うScala学習用のゲームです。Ruby Warriorにインスパイアされて開発したもので、楽しみながらScalaを学ぶことができます。このトークでは私たちがScala Warriorの開発に至った経緯、Scala Warriorの実装を支えるScala.jsの利用方法、そしてScala.jsを活用したタイプセーフなWeb開発について紹介します。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
