### ISSUE TITLE
CFP from 伊藤竜一(amaya) : シンタックスシュガーの甘い罠

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#174]
---
name: 伊藤竜一(amaya)
title: シンタックスシュガーの甘い罠
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: amaya382
github: amaya382
icon: 
organization: 
tags:
  - Best Practices, Intro to Scala

---
Scalaには記述性･可読性のために多くのシンタックスシュガーが存在します. しかしながら, 他言語では見られないようなScala特有のものも含まれ, 初学者にとってはかえって難しく感じられてしまうことがあります. そこで今回は具体的な(少しトリッキーな！)コードを通してScalaにおけるシンタックスシュガーに慣れることを目標とします.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
