### ISSUE TITLE
CFP from Silvia Pina:Beauty and/or elegance in Functional Programming

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#177]
---
name: Silvia Pina
title: Beauty and/or elegance in Functional Programming
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: smourapina
github: 
icon: 
organization: Zalando SE
tags:
  - Functional Programming

---
Beauty is a combination of pleasing traits, and is not exclusive to art, as it applies to disciplines like mathematics. Debates about beauty / code elegance may be implicit but are at the heart of many concerns of modern software development, and contribute positively to quality metrics. Functional programming, coupled with Category Theory, can represent a plethora of well-defined patterns used to cut through the boilerplate and emphasize the purpose of code. We will explore how we use functional programming to achieve beauty in code, and how that translates to high quality software projects.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
