### ISSUE TITLE
CFP from Marconi Lanna:Beautiful Scala

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#180]
---
name: Marconi Lanna
title: Beautiful Scala
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: https://twitter.com/scalafacts
github: https://github.com/marconilanna/
icon: 
organization: Originate
tags:
  - Functional Programming, Best Practices, Intro to Scala

---
Scala is a powerful language. With its flexible and expressive syntax - concise yet not terse - even a single line of Scala can leverage an impressive amount of JVM power. It is the static language that feels dynamic.

In this fun and engaging interactive talk (entirely live from the Scala REPL), I present dozens of Scala snippets that show us how to get dynamic productivity in a statically typed language.

It is not about short or overly clever code. It's about writing clear and elegant code.

Don't forget to bring your REPL!

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
