### ISSUE TITLE
CFP from Melinda Seckington:The Sci-Fi Captains’ Guide To Being A Lead Developer

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#185]
---
name: Melinda Seckington
title: The Sci-Fi Captains’ Guide To Being A Lead Developer
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: mseckington
github: mseckington
icon: 
organization: FutureLearn
tags:
  - Best Practices
---
Space: the final frontier. These are the voyages of a lead developer. Her continuing mission: to explore strange new teams, to seek out new devs and new implementations, to boldly go where no one has gone before. 
 
This talk will look at some of the most beloved sci-fi captains of all time and highlight the lessons that we as tech leads can learn from them.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
