### ISSUE TITLE
CFP from Jonathan WINANDY:7 key recipes for Data Engineering in Scala and Spark

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#192]
---
name: Jonathan WINANDY
title: 7 key recipes for Data Engineering in Scala and Spark
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: ahoy_jon
github: ahoy-jon
icon: 
organization: UNIVALENCE
tags:
  - Big Data / Fast Data, Best Practices, Software Design and Architecture
---
After the construction of several datalakes and large business intelligence pipelines, we now know that the use of Scala and its principles were essential to the success of those large undertakings.

In this talk, we will go through the 7 key scala-based architectures and methodologies that were used in real-life projects. More specifically, we will see the impact of these recipes on Spark performances, and how it enabled the rapid growth of those projects.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。
