### ISSUE TITLE
CFP from 阿部智晃 : ScalaでJavaのSDK使う話。

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#194]
---
name: 阿部智晃
title: ScalaでJavaのSDK使う話。
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: 
github: 
icon: 
organization: 株式会社ココラブル
tags:
  - Intro to Scala, Others
---
越境EC事業を行なっており、AmazonやeBayで販売をしています。それに関連してAmazonのAPI（マーケットプレイスWebサービス(MWS)）やeBayのAPIを利用しレポートの作成を行なっています。
それぞれのサービスで（公式に）共通して提供されているSDKの中にJavaがありましたのでScalaからそれらを利用し開発することにしました。
その時に苦労した点などを紹介できればと思います。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
