### ISSUE TITLE
CFP from Lloyd Chan:Building a smile-detector w/ Scala and OpenCV

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#195]
---
name: Lloyd Chan
title: Building a smile-detector w/ Scala and OpenCV
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: meta_Lloyd
github: lloydmeta
icon: 
organization: 
tags:
  - Functional Programming, Tools, Best Practices, Others
---
A short talk describing how to painlessly use OpenCV from Scala and how to connect it with Akka Stream. Using the data we accumulate, we can train a Spark Support Vector Machine to classify smiling and non-smiling faces. Finally, using that trained classifier, we can build an app that can identify smiling and non-smiling faces in a video stream.

Parts of this talk are available here in blog form: 
1. https://beachape.com/blog/2016/03/08/scala-and-opencv-ep-1-akka-webcam/
2. https://beachape.com/blog/2016/03/14/scala-and-opencv-ep-2-akka-face-detector/

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
