### ISSUE TITLE
CFP from 島本多可子 : 必殺（本当に死ぬ）！ブロッキング＆ハイパーコンテキストスイッチングパターン

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#196]
---
name: 島本多可子
title: 必殺（本当に死ぬ）！ブロッキング＆ハイパーコンテキストスイッチングパターン
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: @chibochibo03
github: shimamoto
icon: 
organization: 株式会社ビズリーチ
tags:
  - Best Practices, Intro to Scala
---
どんな言語にもダメなコードというのは存在します。
ついうっかりだったとしても、ダメなコードが及ぼす破壊力がとてつもない現実を目の当たりしました。

Scalaは比較的楽に非同期処理を書けますが、フレームワーク上(PlayやSlick)で起こる本質を見逃すこともあるでしょう。
このセッションでは、そのような非同期処理で一見スッキリしたコードに見えて、あら！実は破滅が起きるコードをお話します。

※ 同じ間違いをしないよう失敗から学ぶことが目的です

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
