### ISSUE TITLE
CFP from 花田 恒一 : Scalafxでの入門GUIプログラミング

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#197]
---
name: 花田 恒一
title: Scalafxでの入門GUIプログラミング
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: @nobkz
github: 
icon: 
organization: 株式会社Groovenauts
tags:
  - Intro to Scala, Software Design and Architecture, Others
---
Scalafx使ったGUIプログラミングを解説し、Scalaの言語自体や、GUIプログラミングの楽しさを紹介したい。Javaなどと比較しながら、Scalaは簡潔に書けることや、また、サンプル実装を用いながら、みなさんがよりよいGUIの実装ができるようなアドバイスを提供できれば良いなと思う。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
