### ISSUE TITLE
CFP from 加藤 潤一 : 	チャットワーク社 Scala導入の失敗と成功の歴史

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#208]
---
name: 加藤 潤一
title: 	チャットワーク社 Scala導入の失敗と成功の歴史
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: j5ik2o
github: j5ik2o
icon: 
organization: チャットワーク
tags:
  - Software Design and Architecture, Others
---
PHPからScala化すると公表してから早2年余り、その間コミュニティの皆さんから賛否両論ある意見をいただきながらも、2016年末にやっとScalaを採用したプロダクト Falconをリリースする予定です！ Falconは、システム移行という難しい問題をクリアする必要があった為、私が「探査機 はやぶさ」に因んでつけたプロダクトコードです。実際に、「探査機 はやぶさ」のように、チームは、目の前に立ち塞がる大きな壁に幾度と遭遇し、その度に一丸となって取り組んできました。その失敗と成功の歴史は、新しい価値を見出す発見のプロセスでもありました。そのため、採用する技術要素やアーキテクチャも変遷を遂げています。今回は、そういった紆余曲折なプロダクトストーリとアーキテクチャの変遷を、プロジェクト初期から関わっている私 加藤からScalaコミュニティのみなさんに、詳らかにフィードバックさせていただきます！

**Comment by tomoco95** [comment]
メールにてタイトル修正の依頼あり。修正後タイトルは下記です。
「ChatWorkのScala採用プロダクト “Falcon” リリースまでの失敗と成功の歴史」

メール返信済み、WEBサイトにも掲載しました。closeします。
