### ISSUE TITLE
CFP from Hiromichi Kishi : ゲームサーバのためのScala/Play

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#211]
---
name: Hiromichi Kishi
title: ゲームサーバのためのScala/Play
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: h_kishi
github: 
icon: 
organization: アクセルマーク株式会社
tags:
  - Best Practices, DevOps, Software Design and Architecture
---
我々のモバイルゲーム開発チームではサーバサイドの実装にScala/Playを導入しています。
モバイルゲームのサーバ開発では、大規模なプレイヤーに対して複雑なロジックの機能を素早く提供することと、高スループットでバグの少ない堅牢なシステムを維持し続けることが常に求められています。
このセッションでは、現在本番運用中のタイトルおよび開発中のタイトルの開発から得られた実践的なノウハウを共有します。
デプロイやチューニングなどのAPIサーバとしての話から、暗号化やキャッシュなどゲームサーバとしての独自の工夫の話まで紹介できればと思います。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
