### ISSUE TITLE
CFP from Mikołaj Koziarkiewicz:You think you know ScalaTest?

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#212]
---
name: Mikołaj Koziarkiewicz
title: You think you know ScalaTest?
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: 
github: mikolak-net
icon: 
organization: SoftwareMill
tags:
  - Tools, Best Practices, Intro to Scala
---
When coding with ScalaTest, many people end up using only the very basic matchers (equal, be), since invariably it’s faster to just write the tests out than open up the docs.

Unfortunately, this leads to the tests - deprived of the more expressive features of ScalaTest - ending up less self-documenting, having poorly-worded assertions ("true does not equal false"), or just being flat out incorrect.

This talk will demonstrate the most important matchers, and will highlight some ScalaTest quirks, hopefully allowing you to avoid subsequent head-scratching debug sessions.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
