### ISSUE TITLE
CFP from Sally JENKINSON:Websites are a symptom, not the cause

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#213]
---
name: Sally JENKINSON
title: Websites are a symptom, not the cause
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: https://twitter.com/sjenkinson
github: https://github.com/greywillfade/
icon: 
organization: Records Sound the Same
tags:
  - Tools, Best Practices, Others
---
As developers, what we create is hopefully to meet user needs. But when our focus is maybe too specific - thinking ONLY about website functionality rather than other things that have an impact - your project can fail despite being technically great. In this technology agnostic talk we’ll explore how developers can and should be more involved in strategic and transformational direction, through case studies and a set of practical exercises that can be taken away. You’ll leave this talk with an awareness of wider considerations, activities and tools for you to use on your own projects.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
