### ISSUE TITLE
CFP from Chris Phelps:RPC at Real-World Scale

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#214]
---
name: Chris Phelps
title: RPC at Real-World Scale
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: @CJPhelps
github: https://github.com/chrisphelps
icon: 
organization: Tendril
tags:
  - Microservices
---
Finagle is an extensible RPC system for the JVM, developed by Twitter and used by many adopters. We will introduce Finagle concepts including why to choose RPC over REST, how to select a protocol, and how to use filters to add capabilities to your service stack. We will touch briefly on building your own protocol, and will share lessons and recommendations from our experiences running Finagle services in production for over 3 years. Attendees will leave with information they need to determine whether Finagle is a good fit for their organization.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
