### ISSUE TITLE
CFP from Eugene Yokota (eed3si9n) : sbt、JSON ライブラリの歴史、マイクロサービス、スキーマの進化に関して

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#219]
---
name: Eugene Yokota (eed3si9n)
title: sbt、JSON ライブラリの歴史、マイクロサービス、スキーマの進化に関して
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: eed3si9n
github: eed3si9n
icon: 
organization: Lightbend
tags:
  - Tools, Best Practices, Microservices
---
sbt 1.0 に向けた開発を進める中で、僕が開発用のツールとして導入しているものを紹介します。
その前に少し寄り道して Scala における JSON ライブラリの歴史をおさらいして、クラウド・ネイティブなマイクロサービスを開発している Google などをヒントに、徐々に進化することが可能な堅固な API をどう開発できるのかを考察します。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
