### ISSUE TITLE
CFP from Eugene Yokota (eed3si9n) : sbt 0.13.x、sbt サーバー、sbt 1.0 の動向

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#220]
---
name: Eugene Yokota (eed3si9n)
title: sbt 0.13.x、sbt サーバー、sbt 1.0 の動向
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: eed3si9n
github: eed3si9n
icon: 
organization: Lightbend
tags:
  - Tools, Best Practices
---
2014年以降テクノロジ・プリビューとして開発が続けられてきた sbt 0.13.x シリーズのまとめ、次期 sbt において追加される予定の sbt サーバー機能、およびその他の sbt 1.0 に関する解説を開発チームの現行テックリードである @eed3si9n こと Yokota が行う。
ScalaMatsuri が開催される頃には進捗がうまくいっているといいですね。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
