### ISSUE TITLE
CFP from Alexander Podkhalyuzin:Under the hood of Scala Implicits

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#221]
---
name: Alexander Podkhalyuzin
title: Under the hood of Scala Implicits
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: Safela
github: Alefas
icon: 
organization: JetBrains
tags:
  - Tools, Intro to Scala
---
Implicit conversions and parameters are fundamental and unique features of Scala that are powerful at the same time. To use these features to their maximum potential, and do so with confidence, you have to understand the specifics of how Scala compiler’s implicits search works. I will cover this topic in details, including ways you can optimize the implicits search algorithm in your library. The second part will focus on IntelliJ IDEA and how to leverage your IDE for working with implicits. Among other helpful IDE features, I will show how to debug implicits in IntelliJ IDEA.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
