### ISSUE TITLE
CFP from Alexander Podkhalyuzin:Let's talk to akka

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#222]
---
name: Alexander Podkhalyuzin
title: Let's talk to akka
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: Safela
github: Alefas
icon: 
organization: JetBrains
tags:
  - Tools, Software Design and Architecture, Microservices
---
Akka is the best thing, which happened to Scala. So... let's implement chatbot. I will show you in practice how to do it using some specific library, which is built on top of akka. But that's just a story, you will see internals and that's why you will learn how to leverage from such libraries as akka-http and akka-persistence.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
