### ISSUE TITLE
CFP from 渡邉大祐 : 僕たちはAPI構築運用に何を使ったのか！(Finalge, Test, CodeFormat, Functional Programming など)

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#228]
---
name: 渡邉大祐
title: 僕たちはAPI構築運用に何を使ったのか！(Finalge, Test, CodeFormat, Functional Programming など)
length: 15 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: wata_dai
github: 
icon: 
organization: 楽天株式会社
tags:
  - Functional Programming, Tools, Best Practices
---
こういうことありません？
「こういったことをしたいが、どのScalaのライブラリを使えば良いんだろう？」
「ライブラリは知っているが、どのように利用すればいいのだろう」
このセッションでは、僕達が実際に社内向けAPIを構築するにあたって、利用したライブラリを紹介します。どの機能を使ってるのか、何が良いのか、どこで使うのかなどのナレッジのシェアを目的とします。
このセッションが少しでもScalaの導入への足かせを減らし、様々なケースへのScala導入を促進する材料に慣れば幸いです。
例）sbt, Finagle, scrooge, Specs2, ScalaCheck, ScalaMock, scalafmt, scalaz

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
