### ISSUE TITLE
CFP from 小紫弘貴 : 広告配信システムで積み重ねてきたパフォーマンスTips

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#245]
---
name: 小紫弘貴
title: 広告配信システムで積み重ねてきたパフォーマンスTips
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: 
github: petitviolet
icon: 
organization: 
tags:
  - Best Practices
---
広告配信システムには高パフォーマンスが要求されます。
その中で少しでもパフォーマンスを上げるために行ってきた小さな改善があります。
当たり前のことも多いですが、普通ならあまり気にしなくてもいいような、細かいポイントを紹介します。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
