### ISSUE TITLE
CFP from 小紫 弘貴 : Akka-Actorで設計・開発して失敗し、学んだ話

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#246]
---
name: 小紫 弘貴
title: Akka-Actorで設計・開発して失敗し、学んだ話
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: 
github: petitviolet
icon: 
organization: 
tags:
  - Tools, Best Practices
---
最近注目されているアクターモデル。
アクターモデル自体は1970年代には登場していた概念ですが、
オブジェクト指向に慣れたプログラマにとって新しいパラダイムとなるアクターモデルには、勘違いしやすいポイントがたくさんあります。
例えばlet-it-crashやsuperviserなど、アクターモデルの概念をオブジェクト指向的に捉えようとすると、恐らく間違った設計になってしまいます。
Scalaでのアクターモデル実装としてAkka-Actorが注目を集めている今、新しく使い始めようとしている人も多いかと思います。
このセッションでは、Akka-Actorをよりうまく使えるように、そして自分と同じ失敗をしないように、Actorを使った設計・開発の方向についてお話したいと思います。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
