### ISSUE TITLE
CFP from Chris Birchall:Meta-program and/or shapeless all the things!

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#247]
---
name: Chris Birchall
title: Meta-program and/or shapeless all the things!
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: cbirchall
github: cb372
icon: 
organization: Ovo Energy
tags:
  - Functional Programming, Others
---
Metaprogramming using Scala macros is a powerful tool, but macros can look quite scary the first time you see them. I'll try to show you that macros are both useful and fun!

Part 1: introduction to macros, using live coding to demonstrate how they work and what they can do. Examples of implementing a "def macro" and a macro annotation.

Part 2: introduce scala.meta, the next generation of Scala metaprogramming. More live coding.

Part 3: when you should NOT use a macro. A few examples of using shapeless to achieve the same result as writing a macro, but with less effort.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
