### ISSUE TITLE
CFP from Vladimir Kostyukov:Finch: Put Some Types on your HTTP endpoints

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#251]
---
name: Vladimir Kostyukov
title: Finch: Put Some Types on your HTTP endpoints
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: @vkostyukov
github: https://github.com/vkostyukov
icon: 
organization: Twitter, Inc
tags:
  - Functional Programming, Microservices
---
Finch (a Scala combinator library for building HTTP endpoints) is rapidly approaching 1.0 and while its design keeps evolving, the core principles are still the same as in 0.1. In this talk, we'll walk through Finch's only abstraction, an `Endpoint`, and discuss why building an HTTP API in terms of functional combinators is a reasonable idea that promotes an insane level of reusability. We'll see that functional abstractions and APIs don't necessary trade off performance, but could easily be orthogonal to it.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
