### ISSUE TITLE
CFP from Jonathan WINANDY:Advanced EventSourcing in Scala

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#252]
---
name: Jonathan WINANDY
title: Advanced EventSourcing in Scala
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: ahoy_jon
github: ahoy-jon
icon: 
organization: UNIVALENCE
tags:
  - Tools, Best Practices, Software Design and Architecture
---
To take the succession of events in a system as a source of truth is not a new idea, but it has become more and more important recently (notably due to akka-persistence and Lagom). Despite being a common concept, it is a technique with interesting challenges. After a brief summary of the stakes and opportunities that event-sourcing brings, we shall describe in greater detail these principal difficulties, and the means of overcoming them.

On the menu : 
- Reminders about Event Sourcing.
- Patterns / Anti-Patterns.
- Metadata in the field of Streaming.
- Types and serialization.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
