### ISSUE TITLE
CFP from Devon Stewart:Lessons learned migrating to Reactive Streaming Architecture

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#253]
---
name: Devon Stewart
title: Lessons learned migrating to Reactive Streaming Architecture
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: @blast-hardchese
github: https://github.com/blast-hardcheese/
icon: 
organization: Twilio
tags:
  - Functional Programming, Best Practices, Software Design and Architecture
---
In this talk, the speaker will be highlighting best practices, pitfalls, and chronicling the process of migrating a legacy monolithic service into a reactive streaming architecture.

Topics will include:
  - Abstractions with cats
  - FS2
  - Suggested strategies for migrating from a dynamic language (Python) to Scala 2.11+

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。

フォームから飛んできてたtwitterアカウント情報が間違ってたので直しました。
正しくは@blast_hardcheseでした。

closeします。
