### ISSUE TITLE
CFP from Devon Stewart:Making the most of the Future[T]

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#254]
---
name: Devon Stewart
title: Making the most of the Future[T]
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: @blast-hardchese
github: https://github.com/blast-hardcheese/
icon: 
organization: Twilio
tags:
  - Functional Programming, Best Practices, Intro to Scala, Software Design and Architecture
---
In this talk, the speaker will provide insight into how to work with Scala's Future[T] abstraction to avoid blocking and handle failure cases. Common pitfalls and best practices will be highlighted, along with take-home exercises and examples.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。

フォームから飛んできてたtwitterアカウント情報が間違ってたので直しました。
正しくは@blast_hardcheseでした。

closeします。
