### ISSUE TITLE
CFP from Scott Maher:Practical use of Free in Modern Software Projects

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#256]
---
name: Scott Maher
title: Practical use of Free in Modern Software Projects
length: 40 minutes
audience: Advanced: Well acquainted with the domain, little introductory material included in the talk
language: English
twitter: @lazyvalue
github: 
icon: 
organization: Twilio
tags:
  - Functional Programming, Best Practices, Software Design and Architecture, Microservices
---
Describing your program in terms of Algebraic Data Types is a natural way to reduce complexity and separate concerns. As programs grow, their algebras can become large and cumbersome. Breaking up the algebra into smaller components decreases complexity of the interpreters, and allows teams to manage their own algebras to better describe their domains. 

In this talk, the speaker will:
  - Provide examples for designing a realistic microservice with Cats' Free Monad
  - Destructure the service into component algebras, using Cats' Coproduct 
  - Mention other solutions to The Expression Problem

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
