### ISSUE TITLE
CFP from Nivedita Reddy Musku:Code with me in scala

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#257]
---
name: Nivedita Reddy Musku
title: Code with me in scala
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: 
github: 
icon: 
organization: Twilio
tags:
  - Intro to Scala
---
I started learning Scala for more than 6 months now and I can clearly relate to the pain points of a beginner. I intend to provide my audience the ease of using Scala language and how it programming even more easier. I would like to live code and help the audience learn with me. Basic and generic scala concepts and day to day codes to make the audience comfortable in the language is my main goal while delivering this talk.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
