### ISSUE TITLE
CFP from 国平清貴 : Scalaによるサーバレスアーキテクチャ入門

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#259]
---
name: 国平清貴
title: Scalaによるサーバレスアーキテクチャ入門
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: kuchitama
github: kuchitama
icon: 
organization: 株式会社シェアウィズ
tags:
  - DevOps, Software Design and Architecture, Microservices
---
AWS Labmdaに代表されるFunction as a Service(FaaS)が、各クラウドプラットフォームから提供されるようになり、インフラ構成の中でサーバ管理する必要のないサーバレスアーキテクチャが生まれました。
サーバレスアーキテクチャとScalaの相性はどうなのでしょうか。サーバレスアーキテクチャの設計は、Scalaのような関数型言語の思想と共通点も多く、非常に親和性が高いと感じています。
サーバレスアーキテクチャを、より手軽に実現するフレームワークの一つであるServerlessFrameworkはScala、sbtを用いるテンプレートが公式に用意されています。
このセッションでは、難しい話はしません。サーバレスアーキテクチャ/ServerlessFrameworkについて初歩的な知識を紹介しながら、AWS Lambda上でScalaを利用するノウハウを紹介していきます。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
