### ISSUE TITLE
CFP from 高橋俊幸 : オブジェクト指向によるフレームワーク構築とファンクショナルなドメイン記述

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#265]
---
name: 高橋俊幸
title: オブジェクト指向によるフレームワーク構築とファンクショナルなドメイン記述
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: tototoshi
github: tototoshi
icon: 
organization: 
tags:
  - Best Practices, Software Design and Architecture
---
オブジェクト指向と関数プログラミングのハイブリッド言語であるScalaの利点を生かしたアプリケーション設計の一例についてお話しします。
副作用の分離やコンポーネント間の依存関係やライフサイクルの記述、ドメインモデルを純粋に保つ方法やそのドメインモデルの操作などの課題に対して、Scalaの言語機能やテクニックがどのように適用できるかを提示します。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
