### ISSUE TITLE
CFP from 藤井善隆 : Serverless ArchitectureをScalaで構築するぞ

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#277]
---
name: 藤井善隆
title: Serverless ArchitectureをScalaで構築するぞ
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: yoshiyoshifujii
github: yoshiyoshifujii
icon: 
organization: エムオーテックス株式会社
tags:
  - DevOps, Software Design and Architecture, Microservices
---
今回、Serverless Architectureの構築にとことんScalaでチャレンジしました。
AWSのAPI GatewayとLambdaの特徴から、最適な組み合わせと、それらを繋ぎ合わせるsbt-pluginの開発をしました。
また、Serverless Architectureを構築していくと、非同期処理の活用が重要になりますが、AWSのKinesisやLambdaをいかにScalaでつないでいくか。
そのあたりの、ノウハウを紹介させていただきたいと思います。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
