### ISSUE TITLE
CFP from Silvia Pina:Whoa! Algebraic! Data Types!

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#293]
---
name: Silvia Pina
title: Whoa! Algebraic! Data Types!
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: smourapina
github: 
icon: 
organization: 
tags:
  - Functional Programming, Intro to Scala
---
Time for an adventure into algebraic data types (ADTs) in Scala! The classical example of this is the Option type, which represents something that may or not have a value. ADTs can be very useful, by increasing code clarity and reducing the likelihood of errors. We will talk about why we call them "algebraic", and see how we can use them and perform operations over them. Maybe you will even want to write your own ADTs after attending this talk!

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
