### ISSUE TITLE
CFP from Julien Tournay:Exploring recursion schemes and type level programming

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#294]
---
name: Julien Tournay
title: Exploring recursion schemes and type level programming
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: @skaalf
github: jto
icon: 
organization: MFGLabs
tags:
  - Functional Programming, Others
---
This talk is about using Scala as a playground to better understand logic and category theory.

We'll start introducing recursion schemes by playing with fixpoint types.
Then, moving from value level recursion to type level recursion, we'll see how our newly acquired skills can also apply by implementing some of the data structures provided in Shapeless.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
