### ISSUE TITLE
CFP from Grzegorz Wilaszek:Type-level declarative futures orchestration

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#297]
---
name: Grzegorz Wilaszek
title: Type-level declarative futures orchestration
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: wilaszekg
github: wilaszekg
icon: 
organization: 
tags:
  - Functional Programming, Software Design and Architecture
---
Concurrent programming in Scala is much easier due to functional design and monadic context of Futures or similar structures. However, we may benefit from more declarative composition of asynchronous tasks. I will explain a type-level, Shapeless based approach to seamless, declarative and type driven composition that works for any monad and is particularly useful for the asynchronous ones. We’ll see how it was applied to implement an asynchronous dependencies injection library for Akka that is type-safe, declarative, functional and sorts out futures handling in actor model.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
