### ISSUE TITLE
CFP from 松川翼 : 実践CleanArchitecture

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#304]
---
name: 松川翼
title: 実践CleanArchitecture
length: 15 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: @wing_007
github: @ma2k8
icon: 
organization: ㈱リクルートマーケティングパートナーズ
tags:
  - Functional Programming, Software Design and Architecture, Microservices
---
新規開発プロジェクトにCleanArchitectureを採用しました。
プロジェクト構成、コードベースでの工夫した部分や、開発フローの紹介をします。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
