### ISSUE TITLE
CFP from 根来 和輝 : Akka のクラスタをテストする方法

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#305]
---
name: 根来 和輝
title: Akka のクラスタをテストする方法
length: 15 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: negokaz
github: 
icon: 
organization: TIS株式会社
tags:
  - Tools
---
Akka Cluster を使うと復数のサーバーに処理を分散するクラスタシステムを比較的簡単に開発することができます。しかし、クラスタシステムの振る舞いを自動テストするためには、分散環境をシミュレーションするため複数の JVM を起動するなど、いくつかの工夫が必要です。このセッションでは Akka で開発されたクラスタシステムをsbt-multi-jvm や Akka のテストキットなどを用いてテストする方法を解説します。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
