### ISSUE TITLE
CFP from Charles Heckroth:Maintaining a Scala Project of Growing Complexity

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#306]
---
name: Charles Heckroth
title: Maintaining a Scala Project of Growing Complexity
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: https://twitter.com/checkroth
github: https://github.com/checkroth
icon: 
organization: Rakuten Inc.
tags:
  - Functional Programming, Best Practices, Software Design and Architecture
---
Roping in Complexity, Decay, and Duplication in a Growing Scala Project:

Lehman's Laws of software evolution state that as a system evolves, "its complexity increases unless work is done to maintain or reduce it", and that a system "must be continually adapted or it becomes progressively less satisfactory".

I will cover my own process of spotting decaying components of our system, and how my team and I apply functional programming concepts to grow our system without wide-spread, un-maintainable complexity growth.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
