### ISSUE TITLE
CFP from 深井康行 : JDI(Java Debug Interface)とScalaFXで作るGUIツール

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#308]
---
name: 深井康行
title: JDI(Java Debug Interface)とScalaFXで作るGUIツール
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: @fukai_yas
github: fukaiyas
icon: 
organization: 
tags:
  - Tools, Others
---
JDIを利用したツールを題材に、ScalaFXを用いたGUIアプリケーションの実装について解説します。
JDIは、いわゆるブレイクポイントの設置や、クラスロードのイベント等、アプリケーションの実行を監視・制御するためのAPIです。
今回は、JDIを利用したカバレジ取得ツールを、ScalaFXを使ったGUIアプリケーションとして実装します。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
