### ISSUE TITLE
CFP from Luc Bourlier:Scala collections: you entry point into Big Data

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#311]
---
name: Luc Bourlier
title: Scala collections: you entry point into Big Data
length: 40 minutes
audience: Advanced: Well acquainted with the domain, little introductory material included in the talk
language: English
twitter: sky1uc
github: skyluc
icon: 
organization: Lightbend
tags:
  - Big Data / Fast Data, Functional Programming
---
The latest generation of tools for the Big Data are written in Scala. And the APIs for these tools are inspired by the Scala collections.
By comparing the Scala collections API and the APIs of Spark, Flink and Kafka Streams, we will see how knowing the Scala collections allows you to start programming Big Data applications.
And then, we will go a bit further, looking at how the APIs were extended, to provide all the operations needed by Big Data applications.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
