### ISSUE TITLE
CFP from Yoshimasa Niwa : 新サービスをゼロから開発してローンチするのに大切だった3つのこと

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#313]
---
name: Yoshimasa Niwa
title: 新サービスをゼロから開発してローンチするのに大切だった3つのこと
length: 40 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: niw
github: niw
icon: 
organization: Twitter, Inc.
tags:
  - Tools, Best Practices, Software Design and Architecture
---
Scala の会社で新サービスをゼロから開発してローンチするまでに学んだことを、バックエンドでは Finatra, Finagle, Pants, IntelliJ, Aurora 等のライブラリやツールを使った実際に起こった問題やその解決策、フロントエンドでは iOS, Android モバイルアプリとの連携について紹介したいと思います。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
