### ISSUE TITLE
CFP from Bas Geerdink:Predictive analytics with Scala and Spark at ING

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#315]
---
name: Bas Geerdink
title: Predictive analytics with Scala and Spark at ING
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: bgeerdink
github: geerdink
icon: 
organization: ING
tags:
  - Big Data / Fast Data, Functional Programming, Best Practices, Data Science / Machine Learning, Software Design and Architecture
---
ING is a Data Driven Experimental Enterprise, which is heavily investing in big data, analytics and streaming processing. As in many other enterprises, we deal with a large variety of data sources. Some are responsible for primary processes, while others are used to improve the quality of the service and to keep internal operations going on smoothly. In this talk, Bas will share an overview of the architecture and projects at ING that have Scala and Spark at its core. You will explore lessons learned, best practices and code!

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
