### ISSUE TITLE
CFP from 前出祐吾 : Akkaで分散システムの障害に備える

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#316]
---
name: 前出祐吾
title: Akkaで分散システムの障害に備える
length: 40 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: yugolf
github: yugolf
icon: 
organization: TIS株式会社
tags:
  - Software Design and Architecture
---
マイクロサービスにより１つ１つのサービス粒度が小さくなり、ビジネススピードを加速するなど様々な恩恵を受けられるようになりました。
しかし、それは分散システムを構築すること意味し、運用の複雑さや様々な障害に備えなければなりません。
サーキットブレーカー、タイムアウト、隔壁、スプリットブレインリゾルバーなど、Akkaでどう立ち向かうのかを紹介します。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
