### ISSUE TITLE
CFP from Bas Geerdink:The Fortune Teller API: doing data science with Spark and Zeppelin

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#317]
---
name: Bas Geerdink
title: The Fortune Teller API: doing data science with Spark and Zeppelin
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: bgeerdink
github: geerdink
icon: 
organization: ING
tags:
  - Big Data / Fast Data, Data Science / Machine Learning, Software Design and Architecture
---
In this session, we’ll create an application for predicting life events with machine learning technology. A few slides with a common process and AI theory will be our starting point. Next, we'll walk through the architecture and source code of a predictive analytics system, created with Scala and Spark. Join if you want to have an overview of a data science project from start to go-live!

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
