### ISSUE TITLE
CFP from Bas Geerdink:Fast data programming with Scala in the IoT

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#318]
---
name: Bas Geerdink
title: Fast data programming with Scala in the IoT
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: bgeerdink
github: geerdink
icon: 
organization: ING
tags:
  - Big Data / Fast Data, Functional Programming, Best Practices, Data Science / Machine Learning, Software Design and Architecture
---
The Internet of Things is a broad technolgy field. There lots of interesting use cases and upcoming technologies to dive into. This session focusses on the 'back-end' of IoT solutions. After all, all this data has to be processed effectively to be truly meaningfull. For demonstration purposes, a software solution was created with Spark, Kafka and Cassandra to demonstrate these data flows. Join this session to get an overview of a fullblown Scala analytics application according the lambda architecture and reactive manifesto, and to get inspired to set up your own predictive IoT solution!

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
