### ISSUE TITLE
CFP from Otto Chrons:How I learned to stop worrying and love the frontend

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#329]
---
name: Otto Chrons
title: How I learned to stop worrying and love the frontend
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: ochrons
github: ochrons
icon: 
organization: 
tags:
  - Others
---
Scala.js brought Scala to web frontend development, relieving developers from many of the quirks of JavaScript. As support for Scala.js keeps growing, Scala is becoming the best environment for true full-stack web development.

In this talk, you will discover the practices of frontend development in Scala and the benefits it brings. You will also explore the intriguing future of true cross-platform frontend development with Scala.js, Scala for Android and Scala Native for iOS. Scala - the one language to rule them all!

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
