### ISSUE TITLE
CFP from Paul Szulc:Going bananas with recursion schemes for fixed point data types

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#330]
---
name: Paul Szulc
title: Going bananas with recursion schemes for fixed point data types
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: rabbitonweb
github: rabbitonweb
icon: 
organization: Slam Data
tags:
  - Functional Programming
---
In 1991 Erik Meijer et. al published "Functional Programming with Bananas, Lenses, Envelopes and Barbed Wire." This paper is a classic one, widely recognizable in the FP community. Constructs described - known as recursion schemas - have real world applications. Strictly speaking, explicit recursion is the ‘goto’ of pure functional programming.
This talk is about generalization of a very specific recursion schema (called catamorphism) over fixed point data type Fix.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
