### ISSUE TITLE
CFP from Paul Szulc:Make your programs Free. Eye-opener to the very essence of Functional Programming

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#331]
---
name: Paul Szulc
title: Make your programs Free. Eye-opener to the very essence of Functional Programming
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: rabbitonweb
github: rabbitonweb
icon: 
organization: Slam Data
tags:
  - Functional Programming, Software Design and Architecture
---
For me, functional programming was never about switching paradigms just to switch. It was always about sanity. Yes, sanity. The ability to finally do real engineering (to some extent). A safe space where you can reason about your code in isolation. Where modularity actually makes sense. 

Free monad is a concept that forges that idea into practical solution. It allows you to reason about your concerns in isolation and combine them together on a higher level. Programs written with Free are very comprehensible and maintainable (once you know how Free works).

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
