### ISSUE TITLE
CFP from Paul Szulc:Having a cake and eating it too. Introduction to Typeclasses in Scala

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#332]
---
name: Paul Szulc
title: Having a cake and eating it too. Introduction to Typeclasses in Scala
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: rabbitonweb
github: rabbitonweb
icon: 
organization: Slam Data
tags:
  - Functional Programming, Best Practices, Intro to Scala
---
Being in a Scala community, you've probably heard about type classes. Very basic concept that both commonly used among many Scala libraries and at the same time very fundamental to understand any theoretical concepts behind Functional Programming. This short talk is all about explaining what Type classes are, how to use them and how to create them, with strong emphasis on answering the question "why should I even care?". We will focus on both on prons and cons, however speaker will probably be a bit biased towards the former.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
