### ISSUE TITLE
CFP from Paul Szul:Functional Programming? It's all been done before! - The Hitchhiker's Guide to Time Travel

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#333]
---
name: Paul Szul
title: Functional Programming? It's all been done before! - The Hitchhiker's Guide to Time Travel
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: rabbitonweb
github: rabbitonweb
icon: 
organization: Slam Data
tags:
  - Functional Programming
---
Welcome to my latest invention: time-travel machine. Please: jump in and fasten your seatbelts, as we are going for a ride. Where we are going, you ask? I’m going to show you origins of this Functional Programming thingy you’ve been hearing about recently so often. Where exactly are we going? Oh, don’t worry, not that far. You’re going to meet some awesome guys, among few: Alonzo Church, John Backus, John Hughes, Philip Wadler. They wrote some awesome stuff. You’re going to be amazed, you have my word.

Fasten your seatbelts. 90s, 80s and 30s … here we go!

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
