### ISSUE TITLE
CFP from Paul Szulc:Understand type classes in less than 15 min

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#334]
---
name: Paul Szulc
title: Understand type classes in less than 15 min
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: rabbitonweb
github: rabbitonweb
icon: 
organization: Slam Data
tags:
  - Functional Programming
---
This is a "from zero to hero" light talk. Preferable audience are people who want to: 
1. understand any shapeless/scalaz/cats presentation out there (this presentation will give you ability to survive first 10 minutes of mentioned talks) 
2. be enlightened that "monads are just type classes with some laws" (this is not a monad tutorial though) 
3. get the "aha!" moment, realising that they've been using Type classes from time to time, without knowing it

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
