### ISSUE TITLE
CFP from Paul Szulc:Writing your own RDD for fun and profit

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#335]
---
name: Paul Szulc
title: Writing your own RDD for fun and profit
length: 40 minutes
audience: Advanced: Well acquainted with the domain, little introductory material included in the talk
language: English
twitter: rabbitonweb
github: rabbitonweb
icon: 
organization: Slam Dta
tags:
  - Big Data / Fast Data, Tools
---
You all know what RDD stands for, right? You have the mental model of a distributed collection. But have you ever consider writing your own RDD? During this talk we will do just that. We will start by explaining essence of how RDDs are implemented internally, following by semi-live demo, where we will implement few RDDs from the scratch. After this talk you will not only be able to write your own RDD, but you will also have a deeper understanding of how Apache Spark works under the hood. I guarantee fun during the talk and profit during your next job interview.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
