### ISSUE TITLE
CFP from Zhao, Zhenhao:From requirements to a running API Service, let automation reduce your work.

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#336]
---
name: Zhao, Zhenhao
title: From requirements to a running API Service, let automation reduce your work.
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: 
github: 
icon: 
organization: Rakuten
tags:
  - Tools, DevOps
---
    As my team is developing API using Scala, this talk is an introduction to the tools my team are using when we work from client's requirements to a finally running API service, and how we make use of these tools.
    These tools make it possible for our clients to interact with our APIs from the very beginning, provide more automation to reduce our effort in development and test, makes our deploy more scalable and makes our running services more reliable.
    What will be introduced in this talk mainly include Thrift, Jenkins, Artifactory, Ansible, Supervisor, Splunk, Open Stack and Docker.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
