### ISSUE TITLE
CFP from Anatolii Kmetiuk:Real-world Category Theory

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#339]
---
name: Anatolii Kmetiuk
title: Real-world Category Theory
length: 40 minutes
audience: Advanced: Well acquainted with the domain, little introductory material included in the talk
language: English
twitter: AKmetyuk
github: anatoliykmetyuk
icon: 
organization: 
tags:
  - Functional Programming, Tools, Best Practices
---
This talk is about how common type classes from functional programming - Monad, Functor, Applicative and others - can be understood in terms of Category Theory. Also, it attempts to represent the Scala type system in the framework of Category Theory. Finally, it provides examples of how to use this theory and some libraries that are based on it (like Cats and Shapeless) to solve common problems in highly generic and type-safe way.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
