### ISSUE TITLE
CFP from 垂水 秀明 : 週末Scalaエンジニアは今年で卒業！会社にScala採用を決定させるための7つのアクション

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#340]
---
name: 垂水 秀明
title: 週末Scalaエンジニアは今年で卒業！会社にScala採用を決定させるための7つのアクション
length: 15 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: hideA88
github: 
icon: 
organization: 株式会社エフ・コード
tags:
  - Intro to Scala, Others
---
「Scalaを使って製品開発したいです！！」

私は職業プログラマーとして、１番時間を使っているのは会社の製品開発です。
せっかくなら、Scalaでの開発に使いたいと思いました。

幾度もの根回しや提案の末に、会社としてScalaを採用するべきだと納得してもらい、ScalaMatsuriのスポンサーにもなってもらいました。

マネジメント層・他職の人々に納得・積極的に応援してもらうために説明したこと、強調したこと。
トップダウンではない形でScalaを製品開発に採用するまでにしてきたことをシェアできればと思います。

例:
- Scalaをエンジニアの○○で有利になるために導入しましょう！！
- プロジェクトマネージャーにScala採用の味方になってもらうために
- ScalaMatsuriのスポンサーになってもらうために
- 開発メンバーにScalaの勉強に積極的になってもらうために

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
