### ISSUE TITLE
CFP from Mathias Sulser:Building a Scala Team

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#342]
---
name: Mathias Sulser
title: Building a Scala Team
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: suls
github: suls
icon: 
organization: Rakuten, Inc.
tags:
  - Intro to Scala, Others
---
How difficult can it be to build a Scala team from scratch?

Starting from how to introduce Scala tn your organziation to growing and hiring new members: this talk is an experience report of our ongoing experiment about things that worked and things that did not work for us.

The goal is to give you a good idea of what you are up against when starting a new team.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
