### ISSUE TITLE
CFP from Eduardo Gonzalez:Using Deep Learning for Recommendation

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#343]
---
name: Eduardo Gonzalez
title: Using Deep Learning for Recommendation
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: Japanese
twitter: @wm_eddie
github: wmeddie
icon: 
organization: JBS
tags:
  - Data Science / Machine Learning
---
In my previous talk I showed one way of using Word2Vec for recommending similar items.  In this talk I’ll take it further by introducing different ways to use Deep Learning for recommendation systems. The talk will cover the basics for using DeepLearning4J and Scala on GPUs. I’ll also demonstrate how to train a model with some sample data. Finally, I’ll present ways you can deploy it in production. The talk will be light on math but full of code and demos.

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
