### ISSUE TITLE
CFP from 重村道人 : Scalaプロダクトについての省察

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#344]
---
name: 重村道人
title: Scalaプロダクトについての省察
length: 40 分
audience: 初心者: 分野の事前知識を必要としない
language: 日本語
twitter: shigemk2
github: shigemk2
icon: 
organization: 
tags:
  - DevOps, Software Design and Architecture, Others
---
いくつかの会社でいくつかのScalaプロジェクトを担当してみて、得られたグッドノウハウ、バッドノウハウ、Scalaで出来ること、Scalaでは出来ないことなどを、振り返って今後のお役に立てられたら幸いです。

**Comment by tomoco95** [comment]
WEBサイトに掲載しました。closeします。
