### ISSUE TITLE
Alexanderさんのセッションをキャンセル / Ericさんのセッションを移動

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2017.scalamatsuri.org#442]
* 1日目17:30 Room BのAlexanderさんのセッションをキャンセル
* 2日目15:30 Room AのEricさんのセッションを、上記へ移動

**Comment by grimrose** [comment]
2日目の空いたセッションはTBDでいいでしょうか？

**Comment by taisukeoe** [comment]
ありがとうございます。TBDで大丈夫です！
