### ISSUE TITLE
スポンサーCMへのリンクを掲載する

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2017.scalamatsuri.org#463]
現在各スポンサーに掲載可否を確認中。返答期限は4/7まで。

**Comment by tomoco95** [comment]
掲載NGとの回答が来たスポンサーさんはありませんでした。
全社分掲載でよろしくお願いします。

**Comment by grimrose** [comment]
CMのページを作成して、youtubeの埋め込みを並べるイメージですかね？

**Comment by taisukeoe** [comment]
@grimrose 
そうですね！
特にフォーマットの制約はないので、それかタイムテーブルの１日目昼休みのところあたりに、他の講演動画のリンクと同様に列挙するのが楽でいいかもしれません。

**Comment by tomoco95** [comment]
全社分のCMをyoutubeにUPしました。下記のリンクは公開URLと埋め込みコードの一覧です。
https://docs.google.com/spreadsheets/d/1HOqg7x4T8ewzyRkvpo5PfY8Gvdjwph06_P00-QSuBW0/edit?usp=sharing

**Comment by tomoco95** [comment]
#465 にてCM追加して頂いたのでcloseします。
