### ISSUE TITLE
CFP from James Roper:Monolith to Reactive - it's all about architecture

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#61]
---

name: James Roper
title: Monolith to Reactive - it's all about architecture
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: jroper
github: jroper
icon: 
organization: Lightbend
tags:
##   - Software Design and Architecture, Microservices

There are plenty of reactive technologies out there, but these are only the building blocks for building reactive systems, using these technologies to build a system does not necessarily make the system reactive. A reactive system will have a fundamentally different architecture to the traditional monolith found in the enterprise.

This presentation will look at how Lagom and Scala can be used to rearchitect the flow of data through a monolith to replace it with microservices.

**Comment by taisukeoe** [comment]
Zapierからのテストなのでclose
