### ISSUE TITLE
CFP from Guillaume Martres:The state of Dotty, the next-generation Scala compiler

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#70]
---

name: Guillaume Martres
title: The state of Dotty, the next-generation Scala compiler
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: 
github: smarter
icon: 
organization: EPFL
tags:
##   - Functional Programming, Tools

Dotty (http://dotty.epfl.ch) is a new, experimental compiler for Scala. In this talk I'll explain what Dotty is, its current state, our plans for the future and how you can get involved and help shape the future of Scala!

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
