### ISSUE TITLE
CFP from 水島宏太:ScalaプログラマのためのKotlin

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#78]
---

name: 水島宏太
title: ScalaプログラマのためのKotlin
length: 15 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: https://twitter.com/kmizu
github: https://github.com/kmizu
icon: 
organization: 株式会社ドワンゴ
tags:
##   - Others

Androidアプリケーション開発用言語として、JetBrains社が開発しているKotlinが急速に注目を浴びています。
KotlinはJVMのバイトコードを吐き、軽量なランタイムを持っています。また、文法的にはScalaに極めて大きく影響を受けています。そのため、Scalaプログラマにとって非常に学びやすい言語になっています。
この発表では、Scalaプログラマに向けたKotlinの解説を行います。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
