### ISSUE TITLE
CFP from Sébastien Doeraene:The road towards Scala.js 1.0.0 

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#81]
---

name: Sébastien Doeraene
title: The road towards Scala.js 1.0.0 
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: sjrdoeraene
github: sjrd
icon: 
organization: EPFL
tags:
##   - Others

After 4 years of development, we are closing on the 1.0.0 release of Scala.js. In this talk, we will go through a retrospective of the major milestones that brought us where we are: what were the cornerstones of the design of Scala.js, and how we "discovered" them. Then, we will look at the near future, and the last bits that separate us from 1.0.0. This will include a roadmap of sorts of the features that are coming in Scala.js.

Knowledge of Scala.js is not required, but having played with it a bit will help to truly appreciate some of the features we will talk about.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
