### ISSUE TITLE
CFP from Krzysztof Ciesielski:Reactive Kafka with Akka Streams

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#83]
---

name: Krzysztof Ciesielski
title: Reactive Kafka with Akka Streams
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: kpciesielski
github: kciesielski
icon: 
organization: SoftwareMill
tags:
##   - Big Data / Fast Data, Functional Programming, Tools

Apache Kafka is now widely adopted among modern distributed systems. In this presentation we will see how Akka Streams can add even more power to Kafka by exposing it as a reactive stream. We will see some examples of how the Reactive Kafka library can be leveraged to build a well-fitting and elegant match of partitioned, pull-based distributed log and asynchronous, backpressured streaming model.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
