### ISSUE TITLE
CFP from よしだ:ScalikeJDBCとSkinny ORMでDBと仲良くなろう

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#86]
---

name: よしだ
title: ScalikeJDBCとSkinny ORMでDBと仲良くなろう
length: 40 分
audience: 中級者: 分野の基礎は分かるが、細かい所は不安
language: 日本語
twitter: grimrose
github: grimrose
icon: 
organization: Yokohama.groovy
tags:
##   - Tools, Others

ScalikeJDBCは、とてもパワフルかつしなやかなDBアクセスライブラリです。
さらに、Skinny ORMと組み合わせることで、DBと上手に付き合うことが出来るようになります。
業務で1年付き合ってきた経験を元に、DBと正面から向き合うSQLと扱いやすいCRUDなAPIを使った事例を紹介します。

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
