### ISSUE TITLE
CFP from Konrad Malawski:Survival guide for the Streaming world

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#89]
---

name: Konrad Malawski
title: Survival guide for the Streaming world
length: 40 minutes
audience: Intermediate: Familiar with principles, not well versed in specifics
language: English
twitter: ktosopl
github: ktoso
icon: 
organization: Lightbend, Akka Team
tags:
##   - Big Data / Fast Data, Software Design and Architecture, Microservices

Streaming architectures have become all the rage in the recent years. In this talk we'll attempt to disambiguate the common uncertainties where which libraries or tools fit in. At the core of it we'll give special attention to Akka Streams and the Reactive Streams standard which was kickstarted by Lightbend in late 2013 and now is heading towards JDK9. We'll see how those compare to Kafka, Spark, Flink and other streaming solutions. We'll discover that while they all share the word "stream", they're not really the same thing, and rather than competing, they complement very nicely.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
