### ISSUE TITLE
CFP from Alejandro Lujan:My type of spaceship!

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#97]
---

name: Alejandro Lujan
title: My type of spaceship!
length: 40 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: andanthor
github: github.com/alejandrolujan
icon: 
organization: Independent
tags:
##   - Functional Programming, Best Practices, Intro to Scala

Let's join Benny on the journey of his lifetime as he tries to put together the perfect Lego spaceship.

The challenge? describe the pieces using Scala Types, while Lord Enterprise Code tries to thwart his plans by handing him tricky pieces to break his design.

Will Benny learn to describe his pieces so precisely that his creations cannot be sabotaged?

As we play the game, we will explore the thought process behind choosing and creating the right types for different use cases, and contemplate the benefits of doing so - less code, less tests, less hidden conventions and more expressive code.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
