### ISSUE TITLE
CFP from Alejandro Lujan:Writing Microservices with Lagom

### ISSUE THREAD

**Issue by kiris** [scalajp/2017.scalamatsuri.org#98]
---

name: Alejandro Lujan
title: Writing Microservices with Lagom
length: 15 minutes
audience: Beginner: No prior knowledge of the domain
language: English
twitter: andanthor
github: github.com/alejandrolujan
icon: 
organization: Independent
tags:
##   - Software Design and Architecture, Microservices

“Microservice” is the hype word of the day, but if you’re convinced there’s value in breaking down large systems into small services, this talk may be just what you’re looking for.

Lagom is the latest framework brought to you by LightBend,  designed to simplify the development and deployment of microservices over the JVM. It helps developers in three areas: writing, distributing and deploying services.

In this talk, I will show the creation of three services and their interaction. Code will be in Scala, and we will peek into the underlying components of Lagom, such as Akka and Cassandra.

**Comment by tomoco95** [comment]
WEBサイトに掲載したのでcloseします。
